python main.py \
    -- train_or_test train+test \
    -- model_name_or_path roberta-base \
    -- data_type pdtb2 \
    -- data_path /content/drive/MyDrive/IDRR/CorpusData/DRR_corpus/pdtb2.csv \
    -- log_path ./custom_log.log \
    -- output_dir ./ckpt \
    -- batch_size 8 \
    -- eval_steps 5 \
    -- epochs 2 \
    -- seed 2023 \
    -- warmup_ratio 0.0001 \
    -- weight_decay 0.01 \
    -- learning_rate 5e-06